# Generated by Django 2.2 on 2020-02-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20200225_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.Agenda'),
        ),
    ]
