# Generated by Django 2.2 on 2020-02-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20200225_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='agenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agenda.Agenda'),
        ),
    ]
